apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars
  labels:
    app: cars
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cars
  template:
    metadata:
      labels:
        app: cars
    spec:
      containers:
      - name: imagepull-demo
        image: nginx:1.221.0
