apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels
  labels:
    app: hotels
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hotels
  template:
    metadata:
      labels:
        app: hotels
    spec:
      containers:
      - name: crash-demo
        image: nginx:1.21.6
